services:
  apache-php:
    build: ./docker/apache-php
    container_name: symfony-apache-php
    ports:
      - "8080:80"
    volumes:
      - ./symfony:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: symfony-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
